### PR TITLE
Allow upload headers

### PR DESCRIPTION
**Pull request by uorbe001**
This adds a new option on the upload block in the config, allowing headers to be passed through to pkgcloud with the same syntax they use:

```
cloudfiles: {
  prod: {
    'user': 'your Rackspace username',
    'key': 'your Rackspace API key',
    'region': 'DFW',
    'upload': [{
      'container': 'name of your Cloud Files container',
      'src': 'source/static/**/*',
      'dest': 'some/folder/',
      'stripcomponents': 1,
      headers: {
          'access-control-allow-origin': 'something',
          'content-disposition': 'something-else'
      }
    }]
  }
}

```

It is useful if you need to override the file headers, although you might ideally want more granular control over each file

### CODE REVIEW

**Comment by benarent** [comment]
This looks very useful, I would like to see it on master.

**Comment by rtgibbons** [comment]
I agree :)

We have moved from Rackspace to AWS, and I'm no longer using this. That combined with there are no unit tests, I don't necessarily want to start merging in code that might introduce more issues.

If someone wants to step up and gets some test pulled in I'll gladly get them added with admin permissions on here and on npm.

**Comment by rtgibbons** [comment]
I'll go ahead and get this merged into master, i'm just not going to cut a release on it.

**Comment by benarent** [comment]
@rtgibbons Thanks for merging.

I work at Rackspace but am more of a hobbiest grunt users. I've sent a mail and I hope we can find someone here to take the maintenance.

**Comment by kenperkins** [comment]
@rtgibbons I'm happy to do this; I do official SDK dev for Rackspace in Node.js (maintain https://github.com/pkgcloud/pkgcloud). Let me know if and how I can help.

**Comment by uorbe001** [comment]
@rtgibbons @benarent @kenperkins I have another branch on my fork adding mimetypes for the uploaded files automatically, we had to add this because rackspace was serving some of our files with the wrong type. I can create a PR with that branch if you guys think it's interesting?

**Comment by kenperkins** [comment]
@uorbe001 When you say rackspace was serving mime-types incorrectly, can you be more specific? How did those files get uploaded into rackspace? Could the uploading client have been sending the wrong mime type?

**Comment by uorbe001** [comment]
@kenperkins We were (and are) using grunt-cloudfiles as our client to upload the static assets to a rackaspace file container. 

A couple of months ago, some of those files were being served with the wrong mimetype (some css files with image types, for instance). Setting the content type header on the files manually fixed our issue, so I simply added the mimetype header to my fork of grunt-cloudfiles (https://github.com/uorbe001/grunt-cloudfiles/pull/2). As far as I know, pkgcloud doesn't (or didn't at the time) set the mimetype for uploaded files, and we found something on the rackspace docs saying it was important to set the mimetype when uploading files to avoid getting them with the wrong mimetype. We have been using my fork since then, so I can't confirm this is still an issue at the moment.

**Comment by kenperkins** [comment]
`pkgcloud` does actually set the mime type in certain cases:

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/storage/client/files.js#L106

**Comment by uorbe001** [comment]
@kenperkins it might have been fixed since we had this issue, I'm using the same library as pkgcloud is using after all. I'll try changing our upload to use this version of grunt-cloudfiles and let you know if we still have issues with the mimetypes.

**Comment by uorbe001** [comment]
@kenperkins I just tried switching back to grunt-cloudfiles:master and on our first assets change all our mimetypes broke again, we get errors like a png file being served with "application/json" and similar stuff (which breaks pretty much everything). I could give you details about the specific urls etc in private if you want, but for now we are switching back to my fork.

**Comment by benweatherman** [comment]
Sorry to dredge up an old thread, but I think I understand why @uorbe001 is seeing broken mimetypes. `grunt-cloudfiles` is [passing the same object to syncFile](https://github.com/rtgibbons/grunt-cloudfiles/blob/master/tasks/cloudfiles.js#L106) each time through the loop, so `pkgcloud` will fill out `content-type` as @kenperkins mentioned, but only the first time through the loop. Subsequent iterations use the same object, which has the `pkgcloud` modified set of headers instead of the header values we setup in the gruntfile.

I think the best solution would be to deep clone `upload.headers`. Another option might be to [do a clone in pkgcloud](https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/openstack/storage/client/files.js#L94) but that doesn't seem like the right place to do it.

I'll submit a PR for this to this repo, but it looks like @uorbe001 has made a similar change already (though I think the mimetype guessing in `grunt-cloudfiles` is superfluous). Any plans to put these repos together at some point? Maybe with some tests? I'd be happy to help out if anyone has any guidance on these fronts.

**Pull request merged**
