### PR TITLE
Added option to prevent enabling CDN

### PR DESCRIPTION
**Pull request by jeffwhelpley**
I tried to follow your suggestions. I have tested this on my own project and works well. If you don't include any option for 'enableCdn' in your gruntfile or set it to true, then the Rackspace container will be CDN enabled automatically. If, however, you put enableCdn: false in your gruntfile, then the CDN will not be enabled.

### CODE REVIEW

**Comment by rtgibbons** [comment]
One thing I noticed when glancing over this, we are defaulting to the CDN being disabled. Which would break how it currently works.

Do you have any good arguments for one way or the other?

I want to get some tests in the package. I'll work on doing that first, then we can look at merging this in soon after.

**Comment by jeffwhelpley** [comment]
Actually, the default is true per line 15:

```
enableCdn = config.enableCdn !== false;
```

Only if the user explicitly sets the option to false will it be false, otherwise if left empty (i.e. the default) or set to anything else, it will be true. So, I don't believe this should break any existing code.

**Comment by rtgibbons** [comment]
Thanks. In my head I read that completely wrong.

**Comment by rtgibbons** [comment]
We have moved to AWS and I'm no longer using this module regularly. I'm looking for someone to take over maintaining it.

I'm going to go ahead and merge this into master, but I'm not going to cut a release on it. I really want to get unit testing in place to very all of this works before it gets pushed out. But at least it's in master so people can point to it and use it.

**Pull request merged**
