### PR TITLE
Adding support for syncing based on MD5 hash

### PR DESCRIPTION
**Pull request by kenperkins**
I wanted to open this PR even though it's not yet ready for merge. As part of a [pending PR](https://github.com/nodejitsu/pkgcloud/pull/161) I'm authoring for [`pkgcloud`](https://github.com/nodejitsu/pkgcloud) I've added robust CDN container support to the Rackspace storage provider. As part of this change, I've enabled `grunt-cloudfiles` to do the following when uploading:
1. Create and CDN enable the container, if not already created
2. Set the container to CDN enabled if it exists but is not CDN enabled
3. Upload the files based on MD5 hash, only uploading when not found in the container, or the MD5 hash is different.

As this PR depends on publishing the CDN changes to `pkgcloud` it's not yet ready to publish, but I wanted to start the dialog with you sooner.

I also took some liberty and moved to Async vs underscore deferred. I find the Async approach is more explicit and easy to follow/maintain, but I'm happy to negotiate on these points :)

Thanks!

### CODE REVIEW

**Comment by rtgibbons** [comment]
Awesome. Thanks for the work on this. Can't wait to get in and 'kick the tires'

**Comment by kenperkins** [comment]
Just noticed the diff is pretty heinous, almost just easier to look at the code proper. I'm a maintainer on pkgcloud, so I expect the CDN changes to be merged published this week. I'll ping you when we're looking good!

**Comment by kenperkins** [comment]
I have it on good authority that this should be published today (`pkgloud v0.8.2`). Have you had a chance to review this?

**Comment by kenperkins** [comment]
Check that, `pkgcloud v0.8.2` is now published.

**Comment by rtgibbons** [comment]
I read over the changes, it all looked good; I want to get in and run some tests on it (need to find time to write some automated tests)

**Comment by kenperkins** [comment]
Can I help somehow? I'm planning a blog post on this as part of the CDN support in pkgcloud.

**Comment by rtgibbons** [comment]
I'm actually about to implement it on my current project, so if all goes well I'll get it merged here in a bit

**Comment by rtgibbons** [comment]
When uploading multiple files, I'm getting the message below after each file.

> You have already piped to this stream. Pipeing twice is likely to break the request.

**Comment by kenperkins** [comment]
Hmm. I'm pretty sure that was fixed in the latest version of request. 

It doesn't prevent any function, but we may need to bump the package.json  version in `pkgcloud` to fix it. Can you test by just blowing away pkgcloud and reinstalling?

**Comment by rtgibbons** [comment]
I'm running pkgcloud 0.8.2 and request is at version 2.21.0 

(fresh install of grunt-cloudfiles from you fork)

**Comment by kenperkins** [comment]
Hmm, I wonder if @mikeal hasn't published that change yet.

**Comment by rtgibbons** [comment]
Just tested out 0.8.3 - no more errors. I'm going to go ahead and cut a release.

**Comment by rtgibbons** [comment]
Thanks, just published 0.1.0

**Pull request merged**
